name: CI

on: [push, pull_request]

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install Poetry
        uses: dschep/install-poetry-action@v1.2

      - name: Cache Poetry virtualenv
        uses: actions/cache@v1
        id: cache
        with:
          path: ~/.virtualenvs
          key: poetry-$
          restore-keys: |
            poetry-$

      - name: Set Poetry config
        run: |
          poetry config virtualenvs.in-project false
          poetry config virtualenvs.path ~/.virtualenvs

      - name: Install Dependencies
        run: poetry install
        if: steps.cache.outputs.cache-hit != 'false'

      - name: Code Quality
        run: poetry run black . --check



      - name: Python Django Coverage GitHub Action
        uses: actions/python-django-coverage-gitHub-action@v1
        with:
          django-app: 'sample_app'
          minimum-coverage: '86'
    #   - name: Test with pytest
    #     run: poetry run pytest --cov . --cov-fail-under=0

    #   - name: Generate Coverage report
    #     run: coverage run --source='.' manage.py test django_snacks

    #   - name: Validate code coverage
    #     run: coverage report --fail-under=60
        
        